# Generated by Django 2.2.6 on 2019-12-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
                ('iso', models.CharField(max_length=5, unique=True)),
                ('designation', models.CharField(max_length=5, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('flag', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sell', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('change_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='exchange.Currency')),
            ],
        ),
    ]
