# Generated by Django 3.0.3 on 2020-02-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='country_fa',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='designation_en',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='designation_fa',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
