# Generated by Django 2.2.6 on 2019-12-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191129_1232'),
        ('blog', '0002_auto_20191129_1323'),
    ]

    operations = [
    ]
