# Generated by Django 2.2.6 on 2019-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20191201_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='token',
            new_name='iso',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='change',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.AddField(
            model_name='currency',
            name='designation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='flag',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='change_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='sell',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
