# Generated by Django 2.2.6 on 2019-12-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191209_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
